image:
  - Ubuntu2204

skip_branch_with_pr: true

build_script:
  - build/appveyor/build.sh

artifacts:
  - path: build/docker/unreal-speccy-portable_0.0.90_x86_64_sdl2_gles2_angle_curl.dmg
    name: sdl2 gles2 angle curl
